### ISSUE TITLE
Publish to Clojars to get API docs at cljdoc

### ISSUE THREAD

**Issue by holyjak** [Saikyun/miracle.save#3]
Publish the library to clojars to make it possible to show API docs at cljdoc.org (it is mostly an automated process).

**Comment by saikyun** [comment]
Hello holyjak! How do I do this, are there any docs? :) Super new to this.

**Comment by holyjak** [comment]
Simple:

1. Publish to Clojars
2. Click on the cljdoc icon on the clojars page of your library and follow the instructions there :)

**Comment by saikyun** [comment]
Done. :)
